[package]
name = "common_preflight"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serialport = "4.9"
chrono = "0.4"
fs2 = "0.4"
clap = { version = "4.6", features = ["derive"] }
cni_laser_fake_driver = { path = "../cni_laser_fake_driver" }

[workspace]

[[bin]]
name = "common-preflight"
path = "src/main.rs"
